import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Bars from "./assets/menu.png";

export default function Home() {
  const Header = () => {
    return (
      <div
        style={{
          maxWidth: 1000,
          margin: "auto",
          height: 70,
          width: "100%",
          paddingLeft: 20,
          paddingRight: 20,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <div style={{ fontWeight: "bold", fontSize: 18, color: "#000" }}>
          Outcrowd
        </div>
        <Image src={Bars} height="30" width="30" />
      </div>
    );
  };

  return (
    <>
      <Header />

      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <p className={styles.description}>
            A maneira mais facil de criar o seu{" "}
            <code className={styles.code}>negócio digital</code>
          </p>

          <div className={styles.grid}>
            <Link href="/signup">
              <a
                href="https://github.com/vercel/next.js/tree/canary/examples"
                className={styles.card}
              >
                <h2>Cadastro&rarr;</h2>
                <p>Cadastro do seu negócio e comece a vender.</p>
              </a>
            </Link>

            <Link href="/signin">
              <a
                href="https://github.com/vercel/next.js/tree/canary/examples"
                className={styles.card}
              >
                <h2>Login&rarr;</h2>
                <p>Logue em sua conta e acesse o seu negócio.</p>
              </a>
            </Link>
          </div>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Cobertura &rarr;</h2>
              <p>Confira a lista de estabelecimentos que estamos cobrindo.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Academia &rarr;</h2>
              <p>
                Ensinamos tudo que você precisa para que consiga desenvolver em
                nossa rede.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
